insert into movies (id,title,year,duration,genres,synopsis,poster_uri,id_director) 
	values (74512,'Family Plot',1976,120,'Comedy,Crime,Drama,Thriller','A phony psychic/con artist and her taxi driver/private investigator boyfriend encounter a pair of serial kidnappers while trailing a missing heir in California.','https://m.media-amazon.com/images/M/MV5BZWE5NDI0OTktNWZkZi00OTQ5LTg2ZTctNzljNDFmZmYyYWEzXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SY1000_CR0,0,676,1000_AL_.jpg',33);
insert into movies (id,title,year,duration,genres,synopsis,poster_uri,id_director) 
	values (68611,'Frenzy',1972,116,'Thriller','A serial murderer is strangling women with a necktie. The London police have a suspect, but he is the wrong man.','https://m.media-amazon.com/images/M/MV5BMTg0MTg2ODE5Ml5BMl5BanBnXkFtZTgwMzUxMDY0MTE@._V1_SY1000_CR0,0,678,1000_AL_.jpg',33);
insert into movies (id,title,year,duration,genres,synopsis,poster_uri,id_director) 
	values (65112,'Topaz',1969,143,'Drama,Thriller','A French Intelligence Agent becomes embroiled in the Cold War politics first with uncovering the events leading up to the 1962 Cuban Missile Crisis, and then back to France to break up an international Russian spy ring.','https://m.media-amazon.com/images/M/MV5BMTYyZDdiYjEtYmZkMy00Y2EyLWIwOGUtYzdlMzgzZDZkOTQwXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SY1000_CR0,0,660,1000_AL_.jpg',33);
insert into movies (id,title,year,duration,genres,synopsis,poster_uri,id_director) 
	values (61107,'Torn Curtain',1966,128,'Romance,Thriller','An American scientist publicly defects to East Germany as part of a cloak and dagger mission to find the solution for a formula resin before planning an escape back to the West.','https://m.media-amazon.com/images/M/MV5BNTYwODI4NjcwOV5BMl5BanBnXkFtZTgwMzU0OTk5MTE@._V1_.jpg',33);
insert into movies (id,title,year,duration,genres,synopsis,poster_uri,id_director) 
	values (58329,'Marnie',1964,130,'Crime,Drama,Mystery,Romance,Thriller','Mark marries Marnie although she is a habitual thief and has serious psychological problems, and tries to help her confront and resolve them.','https://m.media-amazon.com/images/M/MV5BYjQwZjliMjQtZDg3Yy00MzVmLWI3YTgtYjMxNWNkN2ZhMzg2L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX653_CR0,0,653,999_AL_.jpg', 33);
insert into movies (id,title,year,duration,genres,synopsis,poster_uri,id_director) 
	values (56869,'The Birds',1963,119,'Drama,Horror,Mystery,Romance','A wealthy San Francisco socialite pursues a potential boyfriend to a small Northern California town that slowly takes a turn for the bizarre when birds of all kinds suddenly begin to attack people.','https://m.media-amazon.com/images/M/MV5BMTAxNDA1ODc5MDleQTJeQWpwZ15BbWU4MDg2MDA4OTEx._V1_SY1000_CR0,0,651,1000_AL_.jpg',33);
insert into movies (id,title,year,duration,synopsis,poster_uri,genres,id_director) 
	values (54215,'Psycho',1960,109,'Horror,Mystery,Thriller','A Phoenix secretary embezzles $40,000 from her employer''s client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.','https://m.media-amazon.com/images/M/MV5BNTQwNDM1YzItNDAxZC00NWY2LTk0M2UtNDIwNWI5OGUyNWUxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SY1000_CR0,0,672,1000_AL_.jpg',33);
