version: '3.1'

services:

  db:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DB:-dbmovie}
      MYSQL_USER: ${MYSQL_USER:-movie}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysqldata-movie:/var/lib/mysql
    ports:
      - ${MYSQL_PORT:-3306}:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${ADMIN_VERSION:-latest}
    restart: unless-stopped
    ports:
      - ${ADMIN_PORT:-80}:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  mysqldata-movie:

