version: '3.5'

services:

  admin:
    image: dpage/pgadmin4:6.15
    restart: unless-stopped
    ports:
      - ${PGADMIN_PORT:-80}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      
  db:
    image: postgres:15.1
    restart: unless-stopped
    ports:
      - ${PGADMIN_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-dbmovie}
      POSTGRES_USER: ${POSTGRES_USER:-movie}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - pgdata-movie:/var/lib/postgresql/data
      
volumes:
  pgadmin-data:
  pgdata-movie:

