version: '3.1'

volumes:

  dbstorage:
    name: ${DB_DATA_VOLUME:-sqlserver-dbmovie-data}

services:

  db:
    image: mcr.microsoft.com/mssql/server:${DB_TAG:-2022-latest}
    restart: unless-stopped
    environment:
      ACCEPT_EULA: ${DB_ACCEPT_LICENSE:-N}
      MSSQL_PID: ${DB_EDITION:-Developer}
      # MYSQL_DATABASE: ${DB_DBNAME:-dbmovie}
      # MYSQL_USER: ${DB_USER:-movie}
      # MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MSSQL_SA_PASSWORD: ${DB_ROOT_PASSWORD:-Passw@rd}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - dbstorage:/var/lib/mysql
    ports:
      - ${DB_PORT:-1433}:1433

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:${GUI_TAG:-latest}
  #   restart: unless-stopped
  #   ports:
  #     - ${GUI_PORT:-80}:80
  #   environment:
  #     PMA_ARBITRARY: 1
  #     PMA_HOST: db
  #     PMA_PORT: 3306
