version: '3.5'

volumes:

  dbstorage:
    name: ${DB_DATA_VOLUME:-pg-dbmovie-data}
  guistorage:
    name: ${GUI_DATA_VOLUME:-pg-gui-data}

services:

      
  db:
    image: postgres:${POSTGRES_VERSION:-latest}
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-dbmovie}
      POSTGRES_USER: ${POSTGRES_USER:-movie}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - dbstorage:/var/lib/postgresql/data

  gui:
    image: dpage/pgadmin4:${GUI_TAG:-latest}
    restart: unless-stopped
    ports:
      - ${GUI_PORT:-80}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${GUI_USER:-admin@example.org}
      PGADMIN_DEFAULT_PASSWORD: ${GUI_PASSWORD:-password}
    volumes:
      - guistorage:/var/lib/pgadmin

