version: '3.1'

services:

  db:
    image: mariadb:${MARIADB_VERSION:-latest}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MARIADB_DB:-dbmovie}
      MYSQL_USER: ${MARIADB_USER:-movie}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-password}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mariadata-movie:/var/lib/mysql
    ports:
      - ${MARIADB_PORT:-3306}:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${ADMIN_VERSION:-latest}
    restart: unless-stopped
    ports:
      - ${ADMIN_PORT:-80}:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: ${MARIADB_PORT:-3306}

volumes:
  mariadata-movie:

