version: '3.1'

volumes:

  dbstorage:
    name: ${DB_DATA_VOLUME:-mysql-dbmovie-data}


services:

  db:
    image: mysql:${DB_TAG:-latest}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DBNAME:-dbmovie}
      MYSQL_USER: ${DB_USER:-movie}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-password}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - dbstorage:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${GUI_TAG:-latest}
    restart: unless-stopped
    ports:
      - ${GUI_PORT:-80}:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
