CONN movie/password@localhost/xepdb1

create table person (
	id INTEGER
		GENERATED BY DEFAULT AS IDENTITY 
			(start with 11903874)
		constraint pk_person primary key,
	name varchar2(150) not null,
	birthdate date null
);

create table movie (
	id INTEGER
		GENERATED BY DEFAULT AS IDENTITY 
			(start with 8079269)
		constraint pk_movie primary key,
	title varchar2(300) not null,
	year smallint not null,
	duration smallint null,
	synopsis varchar2(4000) null,
	poster_uri varchar2(300) null,
	color varchar2(20) null,
	pg varchar2(15) null,
	director_id integer null,
	constraint uniq_movie UNIQUE(title, year),
	constraint chk_movie_year CHECK(year >= 1850)
);

create table play(
	movie_id integer not null,
	actor_id integer not null,
	role varchar2(100),
	constraint pk_play primary key(movie_id, actor_id)
);

create table have_genre(
	movie_id integer not null,
	genre varchar2(20) not null,
	constraint pk_have_genre primary key(movie_id, genre)
);

alter table movie add constraint fk_movie_director 
	FOREIGN KEY (director_id)
	references person(id);
alter table play add constraint FK_PLAY_MOVIE 
	FOREIGN KEY (movie_id)
	references movie(id);
alter table play add constraint FK_PLAY_ACTOR 
	FOREIGN KEY (actor_id)
	references person(id);
alter table have_genre add constraint FK_HAVE_GENRE 
	FOREIGN KEY (movie_id)
	references movie(id);


